### ISSUE TITLE
dm-robotics-controllers not compatible with mujoco 2.3.6

### ISSUE THREAD

**Issue by HomerW** [google-deepmind/dm_robotics#18]
Hi! I'm finding that dm-robotics-controllers is not compatible with mujoco 2.3.6. 

To reproduce:
- dm_control==1.0.13
- mujoco==2.3.6
- dm-robotics-controllers==0.5.0

```
from dm_robotics.controllers import cartesian_6d_to_joint_velocity_mapper
params = cartesian_6d_to_joint_velocity_mapper.Parameters()
```
This gives the error
```
[/tmpfs/src/git/dm_robotics-kokoro/cpp/support/include/dm_robotics/support/logging.h:181] Check failed: ptr != nullptr
Aborted (core dumped)
```

Are there plans to support the later versions of Mujco?

**Comment by josechenf** [comment]
MuJoCo 3.0.0 is now supported :)
