### ISSUE TITLE
Update to MuJoCo V3.1.0

### ISSUE THREAD

**Issue by peterdavidfagan** [google-deepmind/dm_robotics#21]
Happy to start a pr for this, latest changes are useful for my project.

**Comment by shacklestone** [comment]
That would be most welcome.  There are a few changes Jean has reported elsewhere that it sounds like we should merge and which you might benefit from, too.

**Comment by shacklestone** [comment]
I'm referring to this:
https://github.com/google-deepmind/dm_robotics/pull/19

**Comment by peterdavidfagan** [comment]
> That would be most welcome. There are a few changes Jean has reported elsewhere that it sounds like we should merge and which you might benefit from, too.

Thanks @shacklestone, I will look to get to this once I start cleaning up my current set of code. I have been able to proceed with 3.0.0 for now, however, I intend to use MuJoCo further for research and teaching materials so will look to update at some point in future.

**Comment by JeanElsner** [comment]
We now have dm-control 1.0.20 + MuJoCo 3.1.6 upstream. Also, there is a new Ubuntu LTS version with Python 3.12 system interpreter. Support for these new software versions would be great. Is anyone working on this yet? I'm very invested in this as well and will look into compatibility and prepare a PR if needed.
